package com.example.myfootball.mockResponse.teams

import com.example.myfootball.data.remote.TeamDetailsResponse
import com.example.myfootball.data.remote.TeamResponse

object TeamsResponseMock {
    val teamsResponse = TeamResponse(
        teams = listOf(
            TeamDetailsResponse(
                idTeam = "133702",
                strTeam = "Ajaccio",
                strLeague = "French Ligue 1",
                strTeamBadge = "https://www.thesportsdb.com/images/media/team/badge/qpxvwy1473505505.png",
                strDescriptionFR = null,
                strCountry = "France",
                strTeamBanner = null
            ),
            TeamDetailsResponse(
                idTeam = "133711",
                strTeam = "Lille",
                strLeague = "French Ligue 1",
                strTeamBadge = "https://www.thesportsdb.com/images/media/team/badge/2giize1534005340.png",
                strDescriptionFR= "Le LOSC Lille, couramment abrégé en LOSC ou Lille OSC, est un club de football français. Fondé à Lille en septembre 1944, il est issu de la fusion de deux clubs basés dans différents quartiers de la ville, l'Olympique lillois et le Sporting Club fivois respectivement créés en 1902 et 1901.\r\n\r\nFort du passé de l'Olympique lillois, vainqueur du premier championnat de France professionnel en 1933, le LOSC est la référence d'après-guerre. En dix ans, le club lillois gagne deux titres de champion de France et cinq coupes de France. Mais ne pouvant plus faire face à ses dettes malgré de nombreuses subventions, le club traverse une longue période difficile, avec plusieurs relégations en Division 2, avant d'échouer en troisième division et d'abandonner son statut professionnel en 1969. Remontant en D2 la saison qui suit, le club est financièrement soutenu avant d'être repris par la mairie de Lille en 1980 sous la forme d'une société d'économie mixte. Le LOSC est privatisé en 1999 après avoir frôlé le dépôt de bilan en 1994. Cette privatisation s'accompagne de résultats sportifs positifs : solidement ancré en Ligue 1 depuis la promotion et le titre de champion de deuxième division en 2000, le club se qualifie régulièrement pour les coupes d'Europe actuelles que sont la Ligue des champions ou la Ligue Europa et réalise le doublé championnat-coupe de France lors de la saison 2010-2011.\r\n\r\nLe club est présidé depuis 2002 par Michel Seydoux, actionnaire majoritaire du club depuis 2004. Les Dogues, surnom attribué aux joueurs évoluant sous le maillot du club, sont entraînés depuis l'été 2013 par René Girard.\r\n\r\nJouant d'abord en alternance dans les stades des deux clubs fusionnés, le LOSC décide plus tard de ne recevoir ses adversaires qu'au stade Victor-Boucquey de l'Olympique lillois, renommé stade Henri-Jooris jusqu'à sa démolition en 1975. Le stade Grimonprez-Jooris a ensuite accueilli jusqu'en 2004 dans Lille intra-muros les rencontres à domicile du club nordiste. Pendant huit ans, le Lille OSC s'est installé provisoirement dans le Stadium Lille Métropole de Villeneuve-d'Ascq puis a emménagé lors de la saison 2012-2013 au stade Pierre-Mauroy, un des cinq plus grands stades de France, également situé à Villeneuve-d'Ascq. Les différentes équipes du club s'entraînent depuis 2004 dans le vaste domaine de Luchin. Basé à Camphin-en-Pévèle, ce centre d'entraînement et de formation sert aussi de siège social du club.",
                strCountry = "France",
                strTeamBanner = "https://www.thesportsdb.com/images/media/team/banner/rturvv1420579158.jpg"
            ),
            TeamDetailsResponse(
                idTeam = "133713",
                strTeam = "Lyon",
                strLeague = "French Ligue 1",
                strTeamBadge = "https://www.thesportsdb.com/images/media/team/badge/blk9771656932845.png",
                strDescriptionFR = "L'Olympique lyonnais, couramment abrégé en OL, est un club de football français fondé en 1950. Le club, basé dans le quartier de Gerland, est présidé depuis juin 1987 par Jean-Michel Aulas et l'équipe est entraînée par Hubert Fournier depuis le 23 mai 2014. Il évolue depuis 1989 en Ligue 1.\r\n\r\nL'Olympique lyonnais évolue dans le Stade de Gerland et s'entraîne au centre Tola Vologe, à Lyon. Il possède à son palmarès sept titres - obtenus consécutivement - de champion de France, cinq Coupes de France et une Coupe de la Ligue, ce qui en fait l'un des clubs les plus titrés du championnat de France.\r\n\r\nLe club connaît son apogée au cours des années 2000 avec sept titres consécutifs de champion de France, ce qui constitue un record françaisnote 2, entre 2002 et 2008, une Coupe de France et une Coupe de la Ligue. La section féminine du club a remporté quant à elle le championnat féminin à neuf reprisesnote 3. En 2007, les sections masculines et féminines remportent chacune leur championnat de France, pour la première fois dans l'histoire du football français. En 2008, l’Olympique lyonnais fait mieux en remportant les deux doublés coupe-championnat, homme et femme. Depuis le milieu des années 2000, la section féminine occupe les plus hauts niveaux du football féminin européen (2 titres successifs en Ligue des champions).\r\n\r\nSur le plan international, le club participe régulièrement à la plus prestigieuse des coupes européennes, la Ligue des champions. Après avoir été membre du G14, organisation des clubs les plus importants et riches d'Europe, jusqu'à sa dissolution en janvier 2008, il fait partie des fondateurs de l'association européenne des clubs.\r\n\r\nAujourd'hui, il est considéré comme l'un des clubs majeurs du football européen, avec douze qualifications en Ligue des champions d'affilée. Depuis 2011, le club rhodanien se base de plus en plus sur son centre de formation. L'Olympique lyonnais est le club français qui a joué le plus de matches européens, puisqu'il est à 212 matches (dont 107 succès) depuis ses débuts dans le fief de l'Inter Milan le 10 décembre 1958.",
                strCountry = "France",
                strTeamBanner = "https://www.thesportsdb.com/images/media/team/banner/xwsrtu1420583914.jpg"
            ),
            TeamDetailsResponse(
                idTeam = "133707",
                strTeam = "Marseille",
                strLeague = "French Ligue 1",
                strTeamBadge = "https://www.thesportsdb.com/images/media/team/badge/uutsyt1473504764.png",
                strDescriptionFR="L'Olympique de Marseille (OM) est un club de football français fondé en août 1899 par René Dufaure de Montmirail. Neuf titres de championnat de France professionnel, dix Coupes de France, trois Coupes de la Ligue, deux Trophées des champions et une Ligue des champions de l'UEFA composent le palmarès du club le plus titré et le plus populaire du football français1.\r\n\r\nLe club joue au stade de l'Huveaune de 1904 à 1937, date à laquelle est inauguré le stade Vélodrome. Auparavant, le club marseillais remporte sa première Coupe de France en 1924 et devient le tout premier club provincial à s'adjuger ce titre.\r\n\r\nMarseille est l'un des clubs qui a joué durant la saison inaugurale 1932-1933 et qui évolue encore en Ligue 1 aujourd'hui. L'OM remporte son premier Championnat en 1937, avant de descendre pour la première fois en seconde division en 1959. Une série de montées et descentes s'effectue dans les années 1960 et la décennie suivante est marquée par le premier doublé Coupe-Championnat de l'histoire du club en 1972.\r\n\r\nAprès une période noire aux débuts des années 1980 où l'OM est proche de la faillite, l'arrivée de Bernard Tapie introduit la période la plus faste du club, avec quatre titres de champion consécutifs, une Coupe de France et la Ligue des champions 1992-1993, qui reste la seule remportée par un club français. L'affaire VA-OM et ses conséquences économiques plongent le club en deuxième division. Depuis sa remontée en 1996, le club se confronte à nouveau à la justice avec l'affaire des comptes de l'OM et n'arrive plus à gagner de titre majeur, malgré notamment deux finales de Coupe UEFA (1999 et 2004). Cette période blanche prend fin avec le titre de champion de France 2009-2010 et trois victoires consécutives en Coupe de la Ligue en 2010, 2011 et 2012.\r\n\r\nLe club est depuis 2011 présidé par Vincent Labrune, l'actionnaire principale étant Margarita Louis-Dreyfus, veuve de Robert Louis-Dreyfus. L'équipe première, entraînée par Marcelo Bielsa depuis le 21 mai 2014, évolue lors de la saison 2014-2015 en première division française pour la soixante-cinquième fois de son histoire.",
                strCountry = "France",
                strTeamBanner = "https://www.thesportsdb.com/images/media/team/banner/rutppp1420732910.jpg"
            ),
            TeamDetailsResponse(
                idTeam = "133714",
                strTeam = "Paris SG",
                strLeague = "French Ligue 1",
                strTeamBadge = "https://www.thesportsdb.com/images/media/team/badge/rwqrrq1473504808.png",
                strDescriptionFR= "Le Paris Saint-Germain Football Club (couramment abrégé en Paris SG ou PSG) est un club de football français basé à Paris, issu de la fusion en 1970 du Stade Saint-Germain, fondé en 1904, et du Paris FC fondé en 1969.\r\n\r\nPrésent en première division depuis 1974, le Paris SG est depuis 2007 le club français y évoluant depuis le plus longtemps sans discontinuité : la saison 2014-2015 est sa 41e saison consécutive dans l'élite. Le club a remporté quatre titres de champion de France en 1986, 1994, 2013 et 2014, huit Coupes de France, quatre Coupes de la Ligue et une Coupe d'Europe des vainqueurs de coupe en 1996, la seule remportée par un club français. Malgré sa jeune existence, ses performances européennes lui valent d'apparaître au troisième rang français (et 49e rang européen) du classement des clubs de football du XXe siècle selon l'IFFHS.\r\n\r\nLe Paris Saint-Germain joue à domicile au Parc des Princes, depuis juillet 1974, et s'entraîne au Centre d'entraînement Ooredoo à Saint-Germain-en-Laye, un lieu hérité du Stade Saint-Germain. Dirigé par Daniel Hechter puis Francis Borelli, le club est racheté en 1991 par le diffuseur du championnat, Canal+, qui mène le club parisien à un certain succès pendant ses premières années. En 2006, le PSG devient la propriété du fonds d'investissement américain Colony Capital, intéressé à la future rénovation du Parc des Princes. En 2011 et 2012, le Qatar Sports Investments, fonds d'investissement souverain de l’émirat du Qatar, rachète à son tour le club, lui apportant des moyens financiers considérables et en fait une des sections du nouveau club omnisports du Paris Saint-Germain. Nasser Al-Khelaïfi devient le président du conseil de surveillance.",
                strCountry = "France",
                strTeamBanner = "https://www.thesportsdb.com/images/media/team/banner/wvaw7l1641382901.jpg"
            ),
            TeamDetailsResponse(
                idTeam = "133719",
                strTeam = "Rennes",
                strLeague = "French Ligue 1",
                strTeamBadge = "https://www.thesportsdb.com/images/media/team/badge/ypturx1473504818.png",
                strDescriptionFR = "Le Stade rennais football club, couramment abrégé en Stade rennais, Stade rennais FC ou SRFC, est un club de football français fondé en 1901. Dans un premier temps club omnisports, il porte le nom de Stade rennais jusqu'à sa fusion avec le Football-club rennais en 1904, devenant alors le Stade rennais université-club. Il dispute ses premières compétitions officielles à partir de 1902 au sein du Comité de Bretagne de l'Union des sociétés françaises de sports athlétiques. En 1912, le club emménage sur un terrain situé au bord de la Vilaine, sur lequel est érigé l'actuel Stade de la route de Lorient.\r\n\r\nAprès avoir brillé dans les compétitions régionales, le Stade rennais se fait un nom au niveau national en atteignant la finale de la Coupe de France en 1922 et 1935. Au cours de cette période, en 1932, le club accède également au statut professionnel. Le stade rennais est l'un des membres fondateurs de la Première division du football français. Avec Marseille, Montpellier, Nice et Metz, Rennes est l'un des clubs qui a joué durant la saison inaugurale 1932-1933 et qui évolue encore en Ligue 1 aujourd'hui.\r\n\r\nDans les années 1960, il s'affirme, sous la houlette de son entraîneur Jean Prouff, comme l'une des meilleures équipes de l'hexagone, remportant par deux fois la Coupe de France en 1965 et 1971.\r\n\r\nCes bons résultats demeurent sans lendemain. Après avoir pris son indépendance vis-à-vis de la structure omnisports pour prendre son nom actuel en 1972, la section football connaît une longue traversée du désert sportive, ponctuée de graves difficultés financières. En 1998, la prise de contrôle de François Pinault et de sa holding Artémis transforme le club en société anonyme sportive professionnelle, permet sa modernisation, et le stabilise en Ligue 1. Il s'installe dans le haut de classement de première division, mais ne parvient pas à ajouter de nouvelles lignes à son palmarès, perdant deux finales de Coupe de France en 2009 et 2014 et une finale de Coupe de la Ligue, en 2013.",
                strCountry = "France",
                strTeamBanner = "https://www.thesportsdb.com/images/media/team/banner/tyvspt1423692142.jpg"
            ),
        )
    )
}